# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-16 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_repository_release_tag_regex'),
        ('plan', '0016_planrepository_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planrepository',
            unique_together=set([('plan', 'repo')]),
        ),
    ]
